### ISSUE TITLE
Is the benchmark-results interface not exported on purpose?

### ISSUE THREAD

**Issue by akuhlens** [stamourv/racket-benchmark#26]

**Comment by akuhlens** [comment]
Currently the benchmark-results struct definitions isn't exported so there is no abstraction over accessing the data from fields of the record. Is this by design? I could see an argument either way, but I was rather surprised by the fact that I couldn't access the data afterwards.

**Comment by stamourv** [comment]
I think that may have been by design, with the goal of providing common statistics as the interface, but I'm not sure that makes sense anyway. I agree that easy access to the raw data would be nice.

Would you like to submit a PR exporting and documenting those?

**Comment by stamourv** [comment]
Sure. I still can't think of a good reason to keep that private.

**Comment by odanoburu** [comment]
I'm facing the same issue too.

I'm happy enough by doing:

```racket
(map (compose1 rest vector->list struct->vector) results)
```

although it would be nice to have this built-in -- I can submit a PR if you'd prefer that @stamourv .

**Comment by stamourv** [comment]
@odanoburu: As I mentioned above, I would be happy to merge such a PR. :)
